"""Environmental APIs: RLS-scoped list + create endpoints for the module tables."""
from rest_framework import serializers, viewsets

from apps.core.v1.permissions import CanManage, IsAdmin

from .models import CarbonTransaction, Department, EmissionFactor, SustainabilityGoal


class EmissionFactorSerializer(serializers.ModelSerializer):
    source_type_label = serializers.CharField(source="get_source_type_display", read_only=True)
    unit_label = serializers.CharField(source="get_unit_display", read_only=True)

    class Meta:
        model = EmissionFactor
        fields = ("id", "public_id", "name", "source_type", "source_type_label",
                  "unit", "unit_label", "factor_value", "effective_from", "is_active")

    def validate_factor_value(self, value):
        if value <= 0:
            raise serializers.ValidationError("Factor must be greater than zero.")
        return value


class CarbonTransactionSerializer(serializers.ModelSerializer):
    department_name = serializers.CharField(source="department.name", read_only=True)
    source_type_label = serializers.CharField(source="get_source_type_display", read_only=True)

    class Meta:
        model = CarbonTransaction
        fields = ("id", "public_id", "department_name", "source_type", "source_type_label",
                  "quantity", "co2e_kg", "occurred_on", "created_at")


class SustainabilityGoalSerializer(serializers.ModelSerializer):
    # Writable FK — the queryset is RLS-scoped, so users can only target
    # departments they're allowed to see.
    department = serializers.PrimaryKeyRelatedField(queryset=Department.objects.all())
    department_name = serializers.CharField(source="department.name", read_only=True)
    metric_label = serializers.CharField(source="get_metric_display", read_only=True)
    status_label = serializers.CharField(source="get_status_display", read_only=True)

    class Meta:
        model = SustainabilityGoal
        fields = ("id", "public_id", "title", "department", "department_name",
                  "metric", "metric_label", "baseline_value", "target_value",
                  "target_date", "status", "status_label")


class DepartmentSerializer(serializers.ModelSerializer):
    manager_name = serializers.CharField(source="manager.get_full_name", read_only=True, default="—")

    class Meta:
        model = Department
        fields = ("id", "public_id", "name", "code", "manager_name",
                  "total_co2e_kg", "esg_score", "is_active")
        read_only_fields = ("total_co2e_kg", "esg_score")


class EmissionFactorViewSet(viewsets.ModelViewSet):
    queryset = EmissionFactor.objects.all()
    serializer_class = EmissionFactorSerializer
    permission_classes = [CanManage]
    http_method_names = ["get", "post"]


class CarbonTransactionViewSet(viewsets.ReadOnlyModelViewSet):
    # Auto-generated by ERP signals — never created by hand.
    queryset = CarbonTransaction.objects.select_related("department").all()
    serializer_class = CarbonTransactionSerializer


class SustainabilityGoalViewSet(viewsets.ModelViewSet):
    queryset = SustainabilityGoal.objects.select_related("department").all()
    serializer_class = SustainabilityGoalSerializer
    permission_classes = [CanManage]
    http_method_names = ["get", "post"]


class DepartmentViewSet(viewsets.ModelViewSet):
    # Only admins create departments (RLS also blocks non-privileged inserts).
    queryset = Department.objects.select_related("manager").all()
    serializer_class = DepartmentSerializer
    permission_classes = [IsAdmin]
    http_method_names = ["get", "post"]
